spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 796823187903-60pfp22fupqhr3a4urcu1e5r27hnkih0.apps.googleusercontent.com
            client-secret: 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
#          keycloak:
#            client-id: oauth2-client-app
#            client-secret: P7441YD2ns92oL4GVtkvOoyBRwOEjA0e
#            client-name: oauth2-client-app
#            authorization-grant-type: authorization_code
#            scope:
#              - openid
#              - profile
#            client-authentication-method: client_secret_basic
#            provider: keycloak
          kakao:
            client-id: d474f8df897fd09ba3ec85bb8b2a0dba
            client-secret: omloSHfzVC2AmyOuFUi8o0WYQIwibLFt
            authorization-grant-type: authorization_code
            client-name: oauth2-lecture
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - openid
              - profile
          naver:
            client-id: k2RIT_ZT8pwquevZcsUh
            client-secret: Q2XN8bH5H6
            client-name: oauth2-lecture
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - profile
              - email
        provider:
#          keycloak:
#            issuer-uri: http://localhost:8081/realms/oauth2
#            authorization-uri: http://localhost:8081/realms/oauth2/protocol/openid-connect/auth
#            user-info-uri: http://localhost:8081/realms/oauth2/protocol/openid-connect/userinfo
#            jwk-set-uri: http://localhost:8081/realms/oauth2/protocol/openid-connect/certs
#            token-uri: http://localhost:8081/realms/oauth2/protocol/openid-connect/token
#            user-name-attribute: preferred_username
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mvc:
    static-path-pattern: /static/**